### ISSUE TITLE
How could you make the Fenvi M2 BCM94360NG working on the CNVi M.2 port?

### ISSUE THREAD

**Issue by michaelsunzy** [luchina-gabriel/GIGABYTE-Z590-VISION-D-10900K-RX-6900XT#1]
Thank you for sharing your Z590 D EFI :D

The M.2 of Z590 D is a CNVi M.2, may I ask that how could you make it working?

**Comment by luchina-gabriel** [comment]
Hi Michael, first slot only works with Intel 11th gen, other slots m2 work perfectly...

**Comment by luchina-gabriel** [comment]
Oh, sorry, m2 fenvi work perfectly too, only replace intel ax200 normally and voila, works 😁

**Comment by luchina-gabriel** [comment]
CNVI Slot, above Battery...

**Comment by michaelsunzy** [comment]
> CNVI Slot, above Battery...

Thanks, that is very interesting. I thought it was a CNVi only port which only supports an Intel CNVi card.
This is the first time I see BCM94360 running in a CNVi slot since 2017.
Thanks for your information.

**Comment by luchina-gabriel** [comment]
we're welcome ✌🏼
