### ISSUE TITLE
Network adapter not working problem

### ISSUE THREAD

**Issue by DrDao** [luchina-gabriel/GIGABYTE-Z590-VISION-D-10900K-RX-6900XT#2]
Hi, I have GIGABYTE-Z590-VISION-D, I have installed macOS Monterey, but the network adapter does not work normally under macOS Monterey. You need to modify the hardware options in the network settings to modify the configuration items to manual mode and the duplex mode to The full-duplex option can work normally. Do you have this problem? This problem has troubled me for many days. I don’t know if the same problem exists in macOS Big Sur. I’m sorry for my bad English. Maybe it’s not very clear.

**Comment by DrDao** [comment]
The configuration is as follows
CPU: i7-10700k
Graphics 1: AMD radeon Vii
Graphics 2: AMD 5700XT
Hard Disk: Samsung 980pro 2T
Hard Disk: Samsung 970 prp 512
Display: Dell u2727qM * 2

**Comment by luchina-gabriel** [comment]
Hi DrDao,

Where you from? I from Brazil, speak Portuguese, my english are not very well... LOL!

My hack with Monterey works perfectly ethernet and others devices/drivers.

Try get this EFI and testing in your hack, i believe that works.

Upgrade your BIOS to F5 version and adjusts (details in BIOS directory).

Best regards,
Gabriel
