### ISSUE TITLE
USB ports not working

### ISSUE THREAD

**Issue by KURTOSAVROS** [luchina-gabriel/GIGABYTE-Z590-VISION-D-10900K-RX-6900XT#3]
Hello. I copied the efi, as I have the same motherboard.
Everything works except the USB ports.
Don't know why.
You have a folder called USBMapping but I am not sure on how to use it...

**Comment by luchina-gabriel** [comment]
Hi, 

There are several mappings I did with the GPUs and in different positions of the PCIe slots.

Sometimes you may need to remap the USBs.

Best regards,
Gabriel

**Comment by KURTOSAVROS** [comment]
Thank you bro. I not too advanced, but I got the usbmap.kext from another build and I twicked some things and my machine works perfectly with Monterey. 
The only problem left is that I can't boot into windows now. I will try to find what you did...
